import Mathlib

noncomputable section
open scoped Topology
open scoped Matrix.Norms.L2Operator
open scoped RealInnerProductSpace
open scoped Gradient
open scoped Matrix
open Filter
open scoped BigOperators

namespace «problem-81»
/-
A sequence of errors (e_K) has convergence rate of order O(h(K)) if there exist constants C > 0 and
K₀∈N such that e_K ≤ Ch(K) for all K ≥ K₀.
-/
def HasConvergenceRateOrder
    (e h : ℕ → ℝ) : Prop :=
  ∃ C > 0, ∃ K₀ : ℕ, ∀ K : ℕ, K₀ ≤ K → e K ≤ C * h K

/-
A worst - case bound over a class P of problems is a bound on sup_P∈P e_K(P), where e_K(P) is the
error after K iterations on problem P.
-/
def worstCaseBound
    (P : Type)
    (ProbSet : Set P)
    (e : ℕ → P → ℝ) : ℕ → ℝ :=
  fun K => sSup (e K '' ProbSet)


/-
Let K ∈ ℕ be a prescribed upper bound on the number of iterations in advance. Consider a convex
optimization problem and the subgradient algorithm applied to it, where f* denotes the optimal value
of the problem, G > 0 denotes a uniform upper bound on the norms of subgradients, and R > 0 denotes
an upper bound on the distance from the initial point to some optimal solution. For an arbitrary
stepsize sequence, let hat f^k denote the smallest objective function value attained among all
points generated by the algorithm in the first k iterations, namely, hat f^k: = min_{0 ≤ i ≤ k}
f(x^i), where x^i is the iterate generated at the i - th iteration. Deduce from this that, for this
class of problems, the convergence rate order O (GR{K}) of the subgradient algorithm cannot be
further improved in the worst case.
-/
theorem subgradient_method_worst_case_rate_not_improvable
    (Problem : Type)
    (ProbSet : Set Problem)
    (e : ℕ → Problem → ℝ)
    (G R : ℝ)
    (hG : 0 < G)
    (hR : 0 < R)
    (hWorstCase_bddAbove :
      ∀ K : ℕ, BddAbove (e K '' ProbSet))
    (hLower :
      ∀ K : ℕ, ∃ P ∈ ProbSet, e K P ≥ (G * R) / (1 + Real.sqrt K))
    : ∀ h : ℕ → ℝ, HasConvergenceRateOrder (worstCaseBound Problem ProbSet e) h →
        ∃ c > 0, ∃ K₀ : ℕ, ∀ K : ℕ, K₀ ≤ K → c * ((G * R) / (1 + Real.sqrt K)) ≤ h K := by
  intro h hRate
  -- Unpack the eventual upper bound on the worst-case error.
  rcases hRate with ⟨C, hC, K₀, hRateBound⟩
  -- Use the reciprocal of the big-O constant as the lower-bound constant.
  have hInvC : 0 < C⁻¹ := inv_pos.mpr hC
  refine ⟨C⁻¹, hInvC, K₀, ?_⟩
  intro K hK
  -- Pick a problem instance whose error attains the prescribed lower estimate.
  rcases hLower K with ⟨P, hPmem, hPbound⟩
  have hPInImage : e K P ∈ e K '' ProbSet := ⟨P, hPmem, rfl⟩
  -- Compare that instance error with the supremum defining the worst-case bound.
  have hPointwise_le_worst : e K P ≤ worstCaseBound Problem ProbSet e K := by
    simpa [worstCaseBound] using le_csSup (hWorstCase_bddAbove K) hPInImage
  -- Transfer the lower estimate from the chosen instance to the worst-case bound.
  have hLowerWorst : (G * R) / (1 + Real.sqrt K) ≤ worstCaseBound Problem ProbSet e K :=
    le_trans hPbound hPointwise_le_worst
  -- Combine the lower estimate with the assumed convergence-rate upper bound.
  have hCombined : (G * R) / (1 + Real.sqrt K) ≤ C * h K :=
    le_trans hLowerWorst (hRateBound K hK)
  -- Divide by the positive constant `C` to obtain the claimed lower bound on `h`.
  rw [inv_mul_le_iff₀ hC]
  exact hCombined

end «problem-81»
