import Mathlib

noncomputable section
open scoped Topology
open scoped Matrix.Norms.L2Operator
open scoped RealInnerProductSpace
open scoped Gradient
open scoped Matrix
open Filter
open scoped BigOperators

namespace «problem-81»
/-
A sequence of errors (e_K) has convergence rate of order O(h(K)) if there exist constants C > 0 and
K₀∈N such that e_K ≤ Ch(K) for all K ≥ K₀.
-/
def HasConvergenceRateOrder
    (e h : ℕ → ℝ) : Prop :=
  ∃ C > 0, ∃ K₀ : ℕ, ∀ K : ℕ, K₀ ≤ K → e K ≤ C * h K

/-
A worst - case bound over a class P of problems is a bound on sup_P∈P e_K(P), where e_K(P) is the
error after K iterations on problem P.
-/
def worstCaseBound
    (P : Type)
    (ProbSet : Set P)
    (e : ℕ → P → ℝ) : ℕ → ℝ :=
  fun K => sSup (e K '' ProbSet)


/-
Let K ∈ ℕ be a prescribed upper bound on the number of iterations in advance. Consider a convex
optimization problem and the subgradient algorithm applied to it, where f* denotes the optimal value
of the problem, G > 0 denotes a uniform upper bound on the norms of subgradients, and R > 0 denotes
an upper bound on the distance from the initial point to some optimal solution. For an arbitrary
stepsize sequence, let hat f^k denote the smallest objective function value attained among all
points generated by the algorithm in the first k iterations, namely, hat f^k: = min_{0 ≤ i ≤ k}
f(x^i), where x^i is the iterate generated at the i - th iteration. Deduce from this that, for this
class of problems, the convergence rate order O (GR{K}) of the subgradient algorithm cannot be
further improved in the worst case.
-/
theorem subgradient_method_worst_case_rate_not_improvable
    (Problem : Type)
    (ProbSet : Set Problem)
    (e : ℕ → Problem → ℝ)
    (G R : ℝ)
    (hG : 0 < G)
    (hR : 0 < R)
    (hWorstCase_bddAbove :
      ∀ K : ℕ, BddAbove (e K '' ProbSet))
    (hLower :
      ∀ K : ℕ, ∃ P ∈ ProbSet, e K P ≥ (G * R) / (1 + Real.sqrt K))
    : ∀ h : ℕ → ℝ, HasConvergenceRateOrder (worstCaseBound Problem ProbSet e) h →
        ∃ c > 0, ∃ K₀ : ℕ, ∀ K : ℕ, K₀ ≤ K → c * ((G * R) / (1 + Real.sqrt K)) ≤ h K := by
  sorry

end «problem-81»
